# Generated by Django 5.0.6 on 2024-06-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=35)),
                ('department_id', models.IntegerField()),
                ('password', models.CharField(max_length=40)),
                ('confirm_password', models.CharField(max_length=40)),
            ],
        ),
    ]
