# Generated by Django 5.0.6 on 2024-06-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_category_complaintstatus_department_faculty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department_id',
            new_name='department',
        ),
    ]
