# Generated by Django 5.0.6 on 2024-06-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_student_id_complaint_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ComplaintStatus',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
