# Generated by Django 5.0.6 on 2024-06-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
