# Generated by Django 5.0.6 on 2024-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_facultyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyuser',
            name='facultyemail',
            field=models.EmailField(default='faculty@complaintportal.com', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='facultyuser',
            name='password',
            field=models.CharField(default='1234', max_length=40),
        ),
    ]
